### DISCUSSION TITLE
snap package

### DISCUSSION THREAD

**Discussion by rominf** [artempyanykh/marksman#161] [Show and tell]
I've made a snap package for `marksman`. It's my first `snap`, so I'm not 100% sure that it's 100% correct, but it works (I've installed it locally and tested with `helix`).

Here it is:
```yaml
name: marksman
base: core18
version: '2023-01-29'
summary: LSP server for Markdown
description: |
  Write Markdown with code assist and intelligence in the comfort of your favourite editor.
grade: stable
confinement: strict

apps:
  marksman:
    command: ./marksman
    plugs:
      - home
      - network-bind

parts:
  marksman:
    plugin: dotnet
    build-packages:
      - make
    dotnet-version: 6.0
    dotnet-runtime-version: '6.0.14'
    source: https://github.com/artempyanykh/marksman
    source-type: git
    source-tag: '2023-01-29'
    override-build: |
      make publishTo DEST=$SNAPCRAFT_PART_INSTALL
      chmod 0755 $SNAPCRAFT_PART_INSTALL/marksman
```

Should I open a PR, so that you could register and distribute it, or should I do it in a separate repository using my own account?
