### ISSUE TITLE
Fail to create file or go to definition on a wiki link when its aboslute path contains an accented character

### ISSUE THREAD

**Issue by EdualcLaiv** [artempyanykh/marksman#274]
## Context

- OS: Windows 11
- Editor: Helix
- Marksman Version: 2023-11-29 release
- wiki.style = "file-stem"

> I didn't try with a different OS or editor.

### Problem 1

- When editing a file, trying to perform a code action to create a file crashes Helix if its wiki link contains an accented character.
  - For example on `[[foobàr]]` or `[[tést]]`

### Problem 2

- Manualy create a file in your project folder. Its absolute path must contain an accented character (either its name or one of its parent folders).
  - For example, let's create a `activité.md` file.
- From Helix, create a wiki link to this file, like `[[activité]]`
  - Note : auto-completion does work despite the accent in the file's name/path.
- Try to go to definiton (`g` and then `d` on Helix) 

![image](https://github.com/artempyanykh/marksman/assets/4270058/ab271ff9-f190-44dd-831b-8384d2048503)
![image](https://github.com/artempyanykh/marksman/assets/4270058/a950c57a-01cf-45b7-a34c-0c3d78fa08b0)

> Note: `go to definition` from a wiki link to a heading containing an accented character, like `[[test#activité]]` works fine.

## my .marksman.toml file

```toml
[core]
markdown.file_extensions = ["md", "markdown"]
text_sync = "full"
incremental_references = false
paranoid = false

[code_action]
toc.enable = true
create_missing_file.enable = true

[completion]
wiki.style = "file-stem"
```
