### ISSUE TITLE
Support lsp_references for tags in frontmatter

### ISSUE THREAD

**Issue by GordianDziwis** [artempyanykh/marksman#335]
The LSP_references functionality is not working as expected for tags defined in the YAML frontmatter of a document. While it correctly identifies and processes tags written inline as `#tag`, it fails to recognize tags listed in the frontmatter section.

Steps to Reproduce:
1. Create a new document with the following YAML frontmatter:
   ```markdown
   ---
   aliases: Title
   tags:
     - tag
     - another_tag
   ---
   ```
2. Attempt to use LSP_references on the tags defined in the frontmatter.
3. Observe that LSP_references does not recognize or process these tags.

Expected Behavior:
LSP_references should identify and process tags defined in the YAML frontmatter, treating them the same way as inline tags (`#tag`).

Actual Behavior:
LSP_references ignores tags defined in the YAML frontmatter and only works with inline tags.

**Comment by artempyanykh** [comment]
Thanks for reporting this @GordianDziwis! YAML frontmatter support in marksman is very limited. It's a good feature to have though!

**Comment by Deluxe8841** [comment]
Would be cool if it supports of different styles of tags:

1. Array style

  ```
  ---
  title: My Note
  date: 2025-09-30
  tags:
    - project
    - urgent
    - idea
  ---
  ```

2. Inline array

  ```
  ---
  title: My Note
  date: 2025-09-30
  tags: [project, urgent, idea]
  ---
  ```

3. Comma-separated string

  ```
  ---
  title: My Note
  date: 2025-09-30
  tags: project, urgent, idea
  ---
  ```

4. Hierarchical / nested tags

  ```
  ---
  title: My Note
  date: 2025-09-30
  tags:
    - project/important
    - idea/brainstorm
  ---
  ```
